### ISSUE TITLE
Credit?

### ISSUE THREAD

**Issue by dcolnar** [shivang1989/playstoreReview#1]
Hey, I forked your code, pulled the stuff from the config file and looped it because I work for a group that has a lot of apps and I needed to grab a lot of reviews. I then used a bunch of regular expressions to pull all the junk out of the file and made similar requests to apple for our iOS apps. Im not sure the best way to credit you for the initial Android code or if you care. Sorry im writing this as an issue there isn't a way to direct message from github that I can see.

**Comment by shivang1989** [comment]
Hi dcolnar,  I am glad that the code has helped you in some way.  I, too, have pulled stuff from config file in some cases. It's more appropriate sometimes. Cheers. 
Regards,
shivang(dot)ice(dot)2010(at-the-rate)gmail(dot)com
